Repository CosmoVisio/frontend, pull requests merged in 2023-12, with the labels that each got.

#4 [SP2] Criação Header e Footer
  package-lock.json
  package.json
  src/assets/EcoPasseiosPElogo.png
  src/components/botton/BottonPrimary.jsx
  src/components/botton/bottonPrimary.css
  src/components/footer/Footer.jsx
  src/components/footer/footer.css
  src/components/header/Header.jsx
  src/components/header/header.css
  src/pages/index.js
  src/styles/globals.css
Labels: Spint: 2

#5 [SP2] Criação da Tela de Login a partir dos Protótipos de Baixa e Média Fidelidade
  public/f3d35c1c67d426c4a63e4dcabde7c2c3.png
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Icons/Logo.jsx
  src/components/Icons/index.js
  src/components/index.js
  src/pages/index.jsx
  src/pages/login/index.js
  src/pages/login/login.jsx
  src/pages/profile.jsx
  src/pages/register.jsx
Labels: Sprint: 2

#7 [SP3] Criação da Tela de Cadastro
  src/pages/register.jsx
  src/pages/register/index.js
  src/pages/register/register.jsx
Labels: Sprint: 3
